### ISSUE TITLE
wpis w pkgbuild

### ISSUE THREAD

**Issue by joksik** [sirlucjan/lucjan-kernels#1]
Zauwazylem ze pkgbuild (wpis wylaczajacy nume) jest taki wpis

`-i -e '/CONFIG_NODES_SHIFT=6/d' \`

natomiast w pliku konfiguracyjnym kernela jest wpis:

CONFIG_NODES_SHIFT=2

czyli prawdopodobnie komenda sed nie odnajdzie poprawnego wpisu w konfigu bo te dwa wiersze roznia sie cyfra 6 i 2

**Comment by sirlucjan** [comment]
Wszystko jest w jak najlepszym porządku. Zobacz sobie wygenerowany config.last - tam nie ma żadnego wpisu o wartości "CONFIG_NODES_SHIFT" natomiast "CONFIG_NUMA=y" zostaje zmieniony na "# CONFIG_NUMA is not set". Możesz zrobić szybki test:

```
[lucjan@archlinux ~]$ zgrep -i CONFIG_NUMA /proc/config.gz
# CONFIG_NUMA is not set
[lucjan@archlinux ~]$ zgrep -i CONFIG_NODES_SHIFT /proc/config.gz
```
Jak widzisz, wartość "CONFIG_NODES_SHIFT" została całkowicie wyłączona czyli sed dobrze spełnia swoją rolę.
