### ISSUE TITLE
DXVK broken

### ISSUE THREAD

**Issue by JDC2389** [sirlucjan/lucjan-kernels#2]
For Overwatch at least, it freezes and hardlocks, changing kernels fixes the issue. No issues with native linux games, csgo runs really good compared to linux-ck.

**Comment by sirlucjan** [comment]
Could you paste some logs when it freezes?

**Comment by JDC2389** [comment]
Here's the log https://pastebin.com/RU2UeKua

**Comment by sirlucjan** [comment]
Please look at:
```
Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
```

and

```
002f:fixme:msvcp:locale__Locimp__Makexloc (0x33ef1c 63 0x62fbb50 (nil)) semi-stub
```
I don't have nvidia card and I can't reproduce this error.

 Please look at:

https://forum.winehq.org/viewtopic.php?f=8&t=30958

**Comment by JDC2389** [comment]
My whole point is I'm running Overwatch great on Linux-ck, just swapping kernels and dxvk is working smooth. I'm not using a docker, idk about that one lol.

**Comment by sirlucjan** [comment]
Probably pds cause problems - you could disable pds.

**Comment by JDC2389** [comment]
How do I disable pds?

**Comment by sirlucjan** [comment]
Edit config and set:

```
# CONFIG_SCHED_PDS is not set
```
and

```
# CONFIG_SMT_NICE is not set
```

**Comment by JDC2389** [comment]
Interesting, pds is not the issue, I built a kernel from the guy who is making the latest esync wine staging builds. Compare what patches he uses to what you're using maybe. https://github.com/Tk-Glitch/PKGBUILDS/tree/master/linux418-tkg thanks anyways. I'm using 4.18 with PDS on this build.

**Comment by sirlucjan** [comment]
Let me know.
