### ISSUE TITLE
cannot resolve "initramfs-lucjan"

### ISSUE THREAD

**Issue by lavrovvv** [sirlucjan/lucjan-kernels#4]
I build your rolling kernel, but when I try to run
`pacman -U "package_name"`
I got something like this: 
```
warning: cannot resolve "initramfs-lucjan", a dependency of "linux-lucjan-git-kernel"
:: The following package cannot be upgraded due to unresolvable dependencies:
      linux-lucjan-git-kernel
```
What I'm doing wrong?

**Comment by sirlucjan** [comment]
You must install the dependency:

https://github.com/sirlucjan/lucjan-kernels/tree/master/depends/mkinitcpio-lucjan

Instructions:

https://github.com/sirlucjan/lucjan-kernels/tree/master/depends
