### ISSUE TITLE
UKSM and lru

### ISSUE THREAD

**Issue by whikk** [sirlucjan/lucjan-kernels#5]
Hello, sorry to bother you, I have two questions, is UKSM effective to use? Can I enable UKSM and lru at the same time?

**Comment by sirlucjan** [comment]
Using UKSM has little effect - especially if you use Plasma 5 and browsers based on the Chromium engine. I can't comment on lru, because I don't use it. If you want to test it - go ahead. If not, after the release of 5.17 I can see for myself if it will work properly.

**Comment by whikk** [comment]
Thanks for your answer. I'll try UKSM first and then wait for the 5.17 release.

**Comment by sirlucjan** [comment]
@whikk I've been using UKSM + LRU for a few hours now and it looks like everything is working.

**Comment by whikk** [comment]
Thank you so much!

**Comment by sirlucjan** [comment]
You're welcome. I left the computer on overnight and compiled some stuff to check the behavior under full load - also no problems at all. Everything works fine.
